### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by lmangani** [tana/rust-m5stickc-plus-test#1]
This is such an awesome example. Thank you so much for sharing it!
Would you be willing to share the build and load instructions to complete this wonderful bootstrap example?

Thanks in advance!

**Comment by tana** [comment]
Nowadays, it is very easy to use Rust on ESP32.
You can just follow the setup instruction of [esp-idf-template](https://github.com/esp-rs/esp-idf-template#prerequisites).
Then you can build and flash this program to your device.

Because the ecosystem of Rust on ESP has been changed since I created this program, I cannot guarantee correct working of this program.

**Comment by lmangani** [comment]
Thanks!
